name: issues
on:
  issues:
    types: [closed]
jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Did I solve your problem?
        uses: peter-evans/create-or-update-comment@ca08ebd5dc95aa0cd97021e9708fcd6b87138c9b
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            I hope we solved your problem.
            
            If you like using Rich, you might also enjoy [Textual](https://textual.textualize.io)
            
